node ./converter/index.js input=Agriculture_horticulture_information_for_Maori_farms_annual.csv json=Agriculture_horticulture_information_for_Maori_farms_annual.json
node ./converter/index.js input=Agriculture_land-use_information_for_Maori_farms_annual.csv json=Agriculture_land-use_information_for_Maori_farms_annual.json
node ./converter/index.js input=Agriculture_livestock_information_for_Maori_farms_annual.csv json=Agriculture_livestock_information_for_Maori_farms_annual.json
node ./converter/index.js input=Business_demography_enterprises_for_Maori_SMEs_annual.csv json=Business_demography_enterprises_for_Maori_SMEs_annual.json
node ./converter/index.js input=Business_operations_rates_activities_annual.csv json=Business_operations_rates_activities_annual.json
node ./converter/index.js input=Busines_demography_enterprises_for_Maori_authorities_annual.csv json=Busines_demography_enterprises_for_Maori_authorities_annual.json
node ./converter/index.js input=LEED_estimates_of_filled_jobs_quarterly.csv json=LEED_estimates_of_filled_jobs_quarterly.json
node ./converter/index.js input=LEED_worker_turnover_rates_quarterly.csv json=LEED_worker_turnover_rates_quarterly.json
